MiniProject/Models/ApiResponse.cs
namespace MiniProject.Models
{
    public class ApiResponse<T>
    {
        public bool success { get; set; }
        public int status { get; set; }
        public string message { get; set; }
        public T? data { get; set; }
    }
}

MiniProject/Models/ErrorViewModel.cs
namespace MiniProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MiniProject/Models/Facility/FacilityModel.cs
using System.ComponentModel.DataAnnotations;

namespace MiniProject.Models.Facility
{
    public class FacilityModel
    {
        public int Id { get; set; }

        [Required, Display(Name = "Code")]
        public string FacilityCode { get; set; }

        [Required, Display(Name = "Name")]
        public string FacilityName { get; set; }

        [Required, Display(Name = "Image")]
        public string FacilityImage { get; set; }

        [Required, Display(Name = "Capacity")]
        public string FacilityMaxCap { get; set; }

        //[Required]
        [Display(Name = "Open")]
        public bool IsOpen { get; set; }

        public IFormFile? UploadedImage { get; set; }
    }
}

MiniProject/Models/Ticket/TicketModel.cs
using System.ComponentModel.DataAnnotations;

namespace MiniProject.Models.Ticket
{
    public class TicketModel
    {
        public int Id { get; set; }
        public int FacilityId { get; set; }
        public string FacilityName { get; set; }
        public string TicketID { get; set; }

        [Required, Display(Name = "Name")]
        public string TicketHolderName { get; set; }

        [Required, Display(Name = "Email"), EmailAddress]
        public string TicketHolderEmail { get; set; }

        public DateTime TicketValidFrom { get; set; }
        public DateTime TicketValidTo { get; set; }
        public int Pax { get; set; }
    }
}

MiniProject/Controllers/Dashboard/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using MiniProject.Models.Ticket;
using MiniProject.Service;

namespace MiniProject.Controllers.Dashboard
{
    public class DashboardController : Controller
    {
        private readonly IFacilityService _facilityService;
        private readonly ITicketService _ticketService;

        public DashboardController(IFacilityService facilityService, ITicketService ticketService)
        {
            _facilityService = facilityService;
            _ticketService = ticketService;
        }

        public async Task<IActionResult> Index()
        {
            var facilitiesGet = await _facilityService.GetAll();
            var facilities = facilitiesGet.data;

            var tickets = await _ticketService.GetAll();

            List<TicketModel> ticketModels = new();
            foreach (TicketModel ticket in tickets.data)
            {
                TicketModel m = ticket;
                m.FacilityName = facilities.Where(x => x.Id == m.FacilityId).FirstOrDefault().FacilityName;

                ticketModels.Add(m);
            }


            return View(ticketModels);
        }
    }
}

MiniProject/Controllers/Facility/FacilityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MiniProject.Models.Facility;
using MiniProject.Service;

//using MiniProject.Service;
using System.Threading.Tasks;

namespace MiniProject.Controllers.Facility
{
    public class FacilityController : Controller
    {
        private readonly IFacilityService _facilityService;


        public FacilityController(IFacilityService facilitySservice)
        {
            _facilityService = facilitySservice;
        }

        public async Task<ActionResult> Index()
        {
            var facilities = await _facilityService.GetAll();
            return View(facilities.data.OrderBy(x => x.FacilityName));
        }

        public ActionResult Create()
        {
            return PartialView("/Views/Facility/_FacilityForm.cshtml", new FacilityModel());
        }

        public async Task<ActionResult> Edit(int id)
        {
            var facility = await _facilityService.GetById(id);
            return PartialView("/Views/Facility/_FacilityForm.cshtml", facility.data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save([FromForm] FacilityModel m)
        {
            try
            {
                string base64 = "";

                if (m.UploadedImage != null && m.UploadedImage.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        m.UploadedImage.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        base64 = Convert.ToBase64String(fileBytes);
                    }
                }
                m.FacilityImage = base64;

                var response = await _facilityService.Save(m);

                return Json(response);
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var response = await _facilityService.Delete(id);
                return Json(response);
            }
            catch
            {
                return View();
            }
        }
    }
}

MiniProject/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MiniProject.Models;

namespace MiniProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MiniProject/Controllers/Ticket/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using MiniProject.Models.Ticket;
using MiniProject.Service;
using System.Threading.Tasks;

namespace MiniProject.Controllers.Ticket
{
    public class TicketController : Controller
    {
        private readonly ITicketService _ticketService;
        private readonly IFacilityService _facilityService;
        public TicketController(ITicketService ticketService, IFacilityService facilityService)
        {
            _ticketService = ticketService;
            _facilityService = facilityService;
        }

        public async Task<IActionResult> Index()
        {
            var facilities = await _facilityService.GetAll();
            return View(facilities.data.Where(x => x.IsOpen).OrderBy(x => x.FacilityName));
        }

        public async Task<IActionResult> Create(int facilityId)
        {
            var facility = await _facilityService.GetById(facilityId);
            return PartialView("/Views/Ticket/_BookTicket.cshtml", new TicketModel() { FacilityId = facilityId, FacilityName = facility.data.FacilityName });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Book([FromForm] TicketModel ticket)
        {
            ticket.TicketID = Guid.NewGuid().ToString();
            var response = await _ticketService.Book(ticket);
            return Json(response);
        }
    }
}

MiniProject/Views/Dashboard/Index.cshtml
@model IEnumerable<MiniProject.Models.Ticket.TicketModel>

@{
    ViewData["Title"] = "Ticket Bookings";
}

<h2>Bookings</h2>

<table id="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.FacilityName)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.TicketID)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.TicketHolderName)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.TicketHolderEmail)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.TicketValidFrom)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.TicketValidTo)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Pax)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>@Html.DisplayFor(x => m.FacilityName)</td>
                <td>@Html.DisplayFor(x => m.TicketID) </td>
                <td>@Html.DisplayFor(x => m.TicketHolderName)</td>
                <td>@Html.DisplayFor(x => m.TicketHolderEmail)</td>
                <td>@Html.DisplayFor(x => m.TicketValidFrom)</td>
                <td>@Html.DisplayFor(x => m.TicketValidTo)</td>
                <td>@Html.DisplayFor(x => m.Pax)</td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function(){
       $("#table").DataTable();
    });
</script>

MiniProject/Views/Facility/Index.cshtml
@model IEnumerable<MiniProject.Models.Facility.FacilityModel>

@{
    ViewData["Title"] = "Facility";
}

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

<div id="main" class="main">
    @Html.AntiForgeryToken()
</div>

<h2>Manage Facility</h2>
<button class="btn btn-primary mb-2" id="btnCreate">Create Facility</button>

<table id="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.FacilityCode)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.FacilityName)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.FacilityImage)

            </th>
            <th>
                @Html.DisplayNameFor(m => m.FacilityMaxCap)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.IsOpen)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var m in Model)
        {
            <tr>

                <td>
                    <input type="hidden" name="Id" value="@m.Id" />
                    @Html.DisplayFor(x => m.FacilityCode)
                </td>
                <td>@Html.DisplayFor(x => m.FacilityName)</td>
                <td><img src="data:image/png;base64,@m.FacilityImage" alt="Facility Image" width="80" height="80" /></td>
                <td>@Html.DisplayFor(x => m.FacilityMaxCap)</td>
                <td>@Html.DisplayFor(x => m.IsOpen)</td>
                <td>
                    <button type="button" class="btn btn-warning btnEdit" data-id="@m.Id">Edit</button>
                    <button type="button" class="btn btn-danger btnDelete" data-id="@m.Id">Delete </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="facilityModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="facilityModalContent"></div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $("#table").DataTable();

        $("#btnCreate").click(function(){
            $.get('/Facility/Create', function(html){
                $("#facilityModalContent").html(html);
                $("#facilityModal").modal('show');
                $.validator.unobtrusive.parse("#facilityForm");

                bindFacilityFormSubmit();
            });
        });

        $(".btnEdit").click(function(){
            var id = $(this).data("id");

             $.get('/Facility/Edit', {id: id}, function(html){
                 $("#facilityModalContent").html(html);
                 $("#facilityModal").modal('show');
                 $.validator.unobtrusive.parse("#facilityForm");

                 bindFacilityFormSubmit();
             });
        });

        $(".btnDelete").click(function(){
            var id = $(this).data("id");
            if(confirm("Are you sure you want to delete this facility?")){
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Delete", "Facility")',
                    data: {id: id},
                    headers: {
                        'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                    },
                    success: function(response){
                        alert(response.message);
                        if(response.success){
                            window.location.reload();
                        }
                    },
                });
            }
            else
            {
                return false;
            }
        });
        

        function bindFacilityFormSubmit() {
            $('#facilityForm').off('submit').on('submit', function (e) {
                e.preventDefault();

                var formData = new FormData(this);
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Save", "Facility")',
                    data: formData,
                    processData: false,
                    contentType: false,
                    headers: {
                        'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                    },
                    success: function (response) {
                        alert(response.message);
                        if (response.success) {
                            $("#facilityModal").modal('hide');
                            window.location.reload();
                        }
                    },
                    error: function (xhr) {
                        console.error(xhr);
                        alert("An error occurred while submitting the form.");
                    }
                });
            });
        }
    });


</script>

MiniProject/Views/Facility/_FacilityForm.cshtml
@model MiniProject.Models.Facility.FacilityModel
@{
    //Layout = null;
    var modalTitle = Model.Id == 0 ? "Create Facility" : "Edit Facility";
}

<form asp-action="Save" method="post" enctype="multipart/form-data" id="facilityForm">
    @Html.AntiForgeryToken()
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="modal-header">
        <h5 class="modal-title">@modalTitle</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <div class="modal-body">
        <div>@Html.HiddenFor(x => x.Id)</div>
        <div class="form-group mb-3">
            <label asp-for="FacilityCode"></label>

            @if(Model.Id == 0) {
                <input asp-for="FacilityCode" class="form-control" />
            }else
            {
                <input asp-for="FacilityCode" class="form-control" readonly/>
            }
            
            <span asp-validation-for="FacilityCode" class="text-danger"></span>
        </div>

        <div class="form-group mb-3">
            <label asp-for="FacilityName"></label>
            <input asp-for="FacilityName" class="form-control" />
            <span asp-validation-for="FacilityName" class="text-danger"></span>
        </div>

        <div class="form-group mb-3">
            <label asp-for="UploadedImage">Upload Image</label>
            <input asp-for="UploadedImage" type="file" class="form-control" />
            <span asp-validation-for="UploadedImage" class="text-danger"></span>
        </div>

        <div class="form-group mb-3">
            <label asp-for="FacilityMaxCap"></label>
            <input asp-for="FacilityMaxCap" class="form-control" />
            <span asp-validation-for="FacilityMaxCap" class="text-danger"></span>
        </div>

        <div class="form-group form-check mb-3">
            <input asp-for="IsOpen" class="form-check-input" />
            <label asp-for="IsOpen" class="form-check-label"></label>
            <span asp-validation-for="IsOpen" class="text-danger"></span>
        </div>

        <div class="modal-footer">
            <button type="submit" class="btn btn-success">Save</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
    </div>
</form>

MiniProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

MiniProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiniProject</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiniProject.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
</head>
<body>
    <header>
        
    </header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Theme Park</a> *@
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="mainNavbar">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Facility" asp-action="Index">Facility</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Ticket" asp-action="Index">Book Tickets</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Dashboard" asp-action="Index">Dashboard Bookings</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MiniProject/Views/Ticket/Index.cshtml
@model IEnumerable<MiniProject.Models.Facility.FacilityModel>

@{
    ViewData["Title"] = "Tickets";
}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

<div class="container mt-4">
    <h2 class="mb-4">Choose a Theme Park</h2>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var m in Model)
        {
            <div class="col">
                <div class="card h-100 book">
                    <img src="data:image/png;base64,@m.FacilityImage" class="card-img-top" alt="@m.FacilityName" style="height: 200px; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">@m.FacilityName</h5>
                        <p class="card-text">@m.FacilityName</p>
                        <button class="btn btn-primary btnBook"
                                data-id="@m.Id">
                            Book Ticket
                        </button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div class="modal fade" id="ticketModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="ticketModalContent"></div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('.btnBook').click(function (){
            var facilityId = $(this).data('id');
            $.get('/Ticket/Create', { facilityId: facilityId }, function (html) {
                $('#ticketModalContent').html(html);
                $('#ticketModal').modal('show');

                 $('#ticketForm').on('submit', function (e) {
                    e.preventDefault();

                    var formData = new FormData(this); 

                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Book", "Ticket")',
                        data: formData,
                        processData: false,
                        contentType: false,
                        success: function (response) {
                            alert(response.message);
                            if (response.success) {
                                window.location.reload();
                            }
                        },
                        error: function (xhr) {
                            alert('An error occurred while saving.');
                        }
                    });
                });
            });
        });
    });
</script>

MiniProject/Views/Ticket/_BookTicket.cshtml
@model MiniProject.Models.Ticket.TicketModel

@{
    ViewData["Title"] = "Tickets";
}

<form asp-action="Book" method="post" id="ticketForm">
    @Html.AntiForgeryToken()
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="modal-header">
        <h5 class="modal-title">Book Ticket</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <div class="modal-body">
        @Html.HiddenFor(x => x.FacilityId);
        <div class="form-group mb-3">
            <label asp-for="FacilityName"></label>
            <input asp-for="FacilityName" class="form-control" disabled/>
        </div>

        <div class="form-group mb-3">
            <label asp-for="TicketHolderName"></label>
            <input asp-for="TicketHolderName" class="form-control" />
            <span asp-validation-for="TicketHolderName" class="text-danger"></span>
        </div>

        <div class="form-group mb-3">
            <label asp-for="TicketHolderEmail"></label>
            <input asp-for="TicketHolderEmail" class="form-control" />
            <span asp-validation-for="TicketHolderEmail" class="text-danger"></span>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Pax"></label>
            <input asp-for="Pax" class="form-control" />
            <span asp-validation-for="Pax" class="text-danger"></span>
        </div>

        <div class="modal-footer">
            <button type="submit" class="btn btn-success">Save</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
    </div>
</form>